baseURL = "https://www.danieleckermann.com/"
languageCode = "en-us"
theme = "hugo-cactus-theme"
title = "Hi, I'm Daniel Eckermann"
[params]
bio = "Partner & CTO at s360 Norway, open-sourcerer and passionate about development"
description = "Partner & CTO at s360 Norway, open-sourcerer and passionate about development"
iconFont = "font-awesome"
name = "Daniel Eckermann"
[social]
github = "https://www.github.com/ecrmnn"
twitter = "https://www.twitter.com/ecrmnn"
